# Generated by Django 5.1.7 on 2025-03-29 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='anons',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Анонс'),
        ),
        migrations.AddField(
            model_name='articles',
            name='title',
            field=models.CharField(default='Без анонса', max_length=200, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
